#!/bin/bash
apt install fish
which fish
echo /usr/bin/fish | sudo tee -a /etc/shells
chsh -s /usr/bin/fish
echo -e "if status is-interactive \n \t cd /home/ \n" >> ~/.config/fish/config.fish
#if [ -z "$1" ]
#  then
#    echo $1 
#fi


echo '# Defined in /usr/share/fish/functions/prompt_hostname.fish @ line 1
                      function prompt_hostname
                          # return the short hostname only by default (#4804)
                          string replace -r ".ru" "" $hostname
                      end' >> ~/.config/fish/config.fish

fish 
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install jorgebucaran/nvm.fish
nvm install 22
nvm use 22
